# Generated by Django 4.0.4 on 2022-06-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='camada',
            new_name='comision',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='apellido',
        ),
    ]
