# Generated by Django 4.0.4 on 2022-06-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_rename_camada_alumno_comision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='curso',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='curso',
            new_name='materia',
        ),
    ]
