# Generated by Django 4.0.4 on 2022-06-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_rename_curso_alumno_materia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia',
            new_name='Carrera',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='materia',
            new_name='carrera',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='materia',
            new_name='carrera',
        ),
    ]
